/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';




  export const getStripeWebhooks = () => {
/**
 * Process incoming Stripe webhook events
 * @summary Handle Stripe webhook
 */
const handleStripeWebhook = <TData = AxiosResponse<string>>(
    handleStripeWebhookBody: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/webhooks/stripe`,
      handleStripeWebhookBody,{
    ...options,}
    );
  }
return {handleStripeWebhook}};
export type HandleStripeWebhookResult = AxiosResponse<string>
