/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { customAxiosInstance } from '../../services/api';



  export const getStripeWebhooks = () => {
/**
 * Process incoming Stripe webhook events
 * @summary Handle Stripe webhook
 */
const handleStripeWebhook = (
    handleStripeWebhookBody: string,
 ) => {
      return customAxiosInstance<string>(
      {url: `/api/webhooks/stripe`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: handleStripeWebhookBody
    },
      );
    }
  return {handleStripeWebhook}};
export type HandleStripeWebhookResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getStripeWebhooks>['handleStripeWebhook']>>>
