/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  FindProductsWithPaginationParams,
  ProductRequest,
  ResponseResultListProductResponse,
  ResponseResultPageProductResponse,
  ResponseResultProductResponse,
  ResponseResultString,
  SearchProductsParams
} from '.././models';

import { customAxiosInstance } from '../../services/api';



  export const getProductManagement = () => {
/**
 * @summary Find product by ID
 */
const findProductById = (
    id: number,
 ) => {
      return customAxiosInstance<ResponseResultProductResponse>(
      {url: `/api/products/${id}`, method: 'GET'
    },
      );
    }
  /**
 * @summary Update the product
 */
const updateProduct = (
    id: number,
    productRequest: ProductRequest,
 ) => {
      return customAxiosInstance<ResponseResultProductResponse>(
      {url: `/api/products/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: productRequest
    },
      );
    }
  /**
 * @summary Delete the product by ID
 */
const deleteProduct = (
    id: number,
 ) => {
      return customAxiosInstance<ResponseResultString>(
      {url: `/api/products/${id}`, method: 'DELETE'
    },
      );
    }
  /**
 * @summary Create new product
 */
const createProduct = (
    productRequest: ProductRequest,
 ) => {
      return customAxiosInstance<ResponseResultString>(
      {url: `/api/products/createProduct`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: productRequest
    },
      );
    }
  /**
 * @summary Find products with pagination
 */
const findProductsWithPagination = (
    params?: FindProductsWithPaginationParams,
 ) => {
      return customAxiosInstance<ResponseResultPageProductResponse>(
      {url: `/api/products`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary Search products by Name
 */
const searchProducts = (
    params: SearchProductsParams,
 ) => {
      return customAxiosInstance<ResponseResultListProductResponse>(
      {url: `/api/products/search`, method: 'GET',
        params
    },
      );
    }
  return {findProductById,updateProduct,deleteProduct,createProduct,findProductsWithPagination,searchProducts}};
export type FindProductByIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getProductManagement>['findProductById']>>>
export type UpdateProductResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getProductManagement>['updateProduct']>>>
export type DeleteProductResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getProductManagement>['deleteProduct']>>>
export type CreateProductResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getProductManagement>['createProduct']>>>
export type FindProductsWithPaginationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getProductManagement>['findProductsWithPagination']>>>
export type SearchProductsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getProductManagement>['searchProducts']>>>
