/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  FindProductsWithPaginationParams,
  ProductRequest,
  ResponseResultListProductResponse,
  ResponseResultPageProductResponse,
  ResponseResultProductResponse,
  ResponseResultString,
  SearchProductsParams
} from '.././models';




  export const getProductManagement = () => {
/**
 * @summary Find product by ID
 */
const findProductById = <TData = AxiosResponse<ResponseResultProductResponse>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/products/${id}`,options
    );
  }
/**
 * @summary Update the product
 */
const updateProduct = <TData = AxiosResponse<ResponseResultProductResponse>>(
    id: number,
    productRequest: ProductRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `/api/products/${id}`,
      productRequest,options
    );
  }
/**
 * @summary Delete the product by ID
 */
const deleteProduct = <TData = AxiosResponse<ResponseResultString>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/api/products/${id}`,options
    );
  }
/**
 * @summary Create new product
 */
const createProduct = <TData = AxiosResponse<ResponseResultString>>(
    productRequest: ProductRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/products/createProduct`,
      productRequest,options
    );
  }
/**
 * @summary Find products with pagination
 */
const findProductsWithPagination = <TData = AxiosResponse<ResponseResultPageProductResponse>>(
    params?: FindProductsWithPaginationParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/products`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * @summary Search products by Name
 */
const searchProducts = <TData = AxiosResponse<ResponseResultListProductResponse>>(
    params: SearchProductsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/products/search`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
return {findProductById,updateProduct,deleteProduct,createProduct,findProductsWithPagination,searchProducts}};
export type FindProductByIdResult = AxiosResponse<ResponseResultProductResponse>
export type UpdateProductResult = AxiosResponse<ResponseResultProductResponse>
export type DeleteProductResult = AxiosResponse<ResponseResultString>
export type CreateProductResult = AxiosResponse<ResponseResultString>
export type FindProductsWithPaginationResult = AxiosResponse<ResponseResultPageProductResponse>
export type SearchProductsResult = AxiosResponse<ResponseResultListProductResponse>
