/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CategoryRequest,
  ResponseResultCategoryResponse,
  ResponseResultListCategoryResponse,
  ResponseResultString
} from '.././models';




  export const getCategoryManagement = () => {
/**
 * Retrieve category details by ID
 * @summary Get category by ID
 */
const getCategoryById = <TData = AxiosResponse<ResponseResultCategoryResponse>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/categories/${id}`,options
    );
  }
/**
 * Update an existing category
 * @summary Update category
 */
const updateCategory = <TData = AxiosResponse<ResponseResultCategoryResponse>>(
    id: number,
    categoryRequest: CategoryRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `/api/categories/${id}`,
      categoryRequest,options
    );
  }
/**
 * Delete a category by ID
 * @summary Delete category
 */
const deleteCategory = <TData = AxiosResponse<ResponseResultString>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/api/categories/${id}`,options
    );
  }
/**
 * Retrieve all active categories
 * @summary Get all categories
 */
const getAllCategories = <TData = AxiosResponse<ResponseResultListCategoryResponse>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/categories`,options
    );
  }
/**
 * Create a new product category
 * @summary Create new category
 */
const createCategory = <TData = AxiosResponse<ResponseResultCategoryResponse>>(
    categoryRequest: CategoryRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/categories`,
      categoryRequest,options
    );
  }
/**
 * Retrieve subcategories by parent category ID
 * @summary Get subcategories
 */
const getSubcategories = <TData = AxiosResponse<ResponseResultListCategoryResponse>>(
    parentId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/categories/${parentId}/subcategories`,options
    );
  }
/**
 * Retrieve top level categories (parentId = 0)
 * @summary Get top level categories
 */
const getTopLevelCategories = <TData = AxiosResponse<ResponseResultListCategoryResponse>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/categories/top-level`,options
    );
  }
return {getCategoryById,updateCategory,deleteCategory,getAllCategories,createCategory,getSubcategories,getTopLevelCategories}};
export type GetCategoryByIdResult = AxiosResponse<ResponseResultCategoryResponse>
export type UpdateCategoryResult = AxiosResponse<ResponseResultCategoryResponse>
export type DeleteCategoryResult = AxiosResponse<ResponseResultString>
export type GetAllCategoriesResult = AxiosResponse<ResponseResultListCategoryResponse>
export type CreateCategoryResult = AxiosResponse<ResponseResultCategoryResponse>
export type GetSubcategoriesResult = AxiosResponse<ResponseResultListCategoryResponse>
export type GetTopLevelCategoriesResult = AxiosResponse<ResponseResultListCategoryResponse>
