/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  CategoryRequest,
  ResponseResultCategoryResponse,
  ResponseResultListCategoryResponse,
  ResponseResultString
} from '.././models';

import { customAxiosInstance } from '../../services/api';



  export const getCategoryManagement = () => {
/**
 * Retrieve category details by ID
 * @summary Get category by ID
 */
const getCategoryById = (
    id: number,
 ) => {
      return customAxiosInstance<ResponseResultCategoryResponse>(
      {url: `/api/categories/${id}`, method: 'GET'
    },
      );
    }
  /**
 * Update an existing category
 * @summary Update category
 */
const updateCategory = (
    id: number,
    categoryRequest: CategoryRequest,
 ) => {
      return customAxiosInstance<ResponseResultCategoryResponse>(
      {url: `/api/categories/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: categoryRequest
    },
      );
    }
  /**
 * Delete a category by ID
 * @summary Delete category
 */
const deleteCategory = (
    id: number,
 ) => {
      return customAxiosInstance<ResponseResultString>(
      {url: `/api/categories/${id}`, method: 'DELETE'
    },
      );
    }
  /**
 * Retrieve all active categories
 * @summary Get all categories
 */
const getAllCategories = (
    
 ) => {
      return customAxiosInstance<ResponseResultListCategoryResponse>(
      {url: `/api/categories`, method: 'GET'
    },
      );
    }
  /**
 * Create a new product category
 * @summary Create new category
 */
const createCategory = (
    categoryRequest: CategoryRequest,
 ) => {
      return customAxiosInstance<ResponseResultCategoryResponse>(
      {url: `/api/categories`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: categoryRequest
    },
      );
    }
  /**
 * Retrieve subcategories by parent category ID
 * @summary Get subcategories
 */
const getSubcategories = (
    parentId: number,
 ) => {
      return customAxiosInstance<ResponseResultListCategoryResponse>(
      {url: `/api/categories/${parentId}/subcategories`, method: 'GET'
    },
      );
    }
  /**
 * Retrieve top level categories (parentId = 0)
 * @summary Get top level categories
 */
const getTopLevelCategories = (
    
 ) => {
      return customAxiosInstance<ResponseResultListCategoryResponse>(
      {url: `/api/categories/top-level`, method: 'GET'
    },
      );
    }
  return {getCategoryById,updateCategory,deleteCategory,getAllCategories,createCategory,getSubcategories,getTopLevelCategories}};
export type GetCategoryByIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCategoryManagement>['getCategoryById']>>>
export type UpdateCategoryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCategoryManagement>['updateCategory']>>>
export type DeleteCategoryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCategoryManagement>['deleteCategory']>>>
export type GetAllCategoriesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCategoryManagement>['getAllCategories']>>>
export type CreateCategoryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCategoryManagement>['createCategory']>>>
export type GetSubcategoriesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCategoryManagement>['getSubcategories']>>>
export type GetTopLevelCategoriesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCategoryManagement>['getTopLevelCategories']>>>
