/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CancelOrderParams,
  CompleteOrderParams,
  CreateOrderParams,
  GetOrderByIdParams,
  GetOrderCountParams,
  GetOrderTokenParams,
  GetUserOrdersParams,
  OrderRequest,
  PayOrderParams,
  ResponseResultListOrderItemResponse,
  ResponseResultLong,
  ResponseResultOrderResponse,
  ResponseResultPageOrderResponse,
  ResponseResultString
} from '.././models';




  export const getOrderManagement = () => {
/**
 * Mark order as shipped (Admin only)
 * @summary Ship order
 */
const shipOrder = <TData = AxiosResponse<ResponseResultString>>(
    orderId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `/api/orders/${orderId}/ship`,undefined,options
    );
  }
/**
 * Process payment for an order
 * @summary Pay order
 */
const payOrder = <TData = AxiosResponse<ResponseResultString>>(
    orderId: number,
    params: PayOrderParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `/api/orders/${orderId}/pay`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Mark order as completed
 * @summary Complete order
 */
const completeOrder = <TData = AxiosResponse<ResponseResultString>>(
    orderId: number,
    params: CompleteOrderParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `/api/orders/${orderId}/complete`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Cancel an order
 * @summary Cancel order
 */
const cancelOrder = <TData = AxiosResponse<ResponseResultString>>(
    orderId: number,
    params: CancelOrderParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `/api/orders/${orderId}/cancel`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Get paginated list of user's orders
 * @summary Get user orders
 */
const getUserOrders = <TData = AxiosResponse<ResponseResultPageOrderResponse>>(
    params: GetUserOrdersParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/orders`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Create a new order from user's selected cart items
 * @summary Create order from cart
 */
const createOrder = <TData = AxiosResponse<ResponseResultOrderResponse>>(
    orderRequest: OrderRequest,
    params: CreateOrderParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/orders`,
      orderRequest,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * @summary Generate token for creating order
 */
const getOrderToken = <TData = AxiosResponse<ResponseResultString>>(
    params: GetOrderTokenParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/orders/generateOrderToken`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Get specific order details
 * @summary Get order by ID
 */
const getOrderById = <TData = AxiosResponse<ResponseResultOrderResponse>>(
    orderId: number,
    params: GetOrderByIdParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/orders/${orderId}`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Get all items in an order
 * @summary Get order items
 */
const getOrderItems = <TData = AxiosResponse<ResponseResultListOrderItemResponse>>(
    orderId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/orders/${orderId}/items`,options
    );
  }
/**
 * Get order details by order number
 * @summary Get order by order number
 */
const getOrderByOrderNo = <TData = AxiosResponse<ResponseResultOrderResponse>>(
    orderNo: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/orders/orderNo/${orderNo}`,options
    );
  }
/**
 * Get total order count for user
 * @summary Get order count
 */
const getOrderCount = <TData = AxiosResponse<ResponseResultLong>>(
    params: GetOrderCountParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/orders/count`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
return {shipOrder,payOrder,completeOrder,cancelOrder,getUserOrders,createOrder,getOrderToken,getOrderById,getOrderItems,getOrderByOrderNo,getOrderCount}};
export type ShipOrderResult = AxiosResponse<ResponseResultString>
export type PayOrderResult = AxiosResponse<ResponseResultString>
export type CompleteOrderResult = AxiosResponse<ResponseResultString>
export type CancelOrderResult = AxiosResponse<ResponseResultString>
export type GetUserOrdersResult = AxiosResponse<ResponseResultPageOrderResponse>
export type CreateOrderResult = AxiosResponse<ResponseResultOrderResponse>
export type GetOrderTokenResult = AxiosResponse<ResponseResultString>
export type GetOrderByIdResult = AxiosResponse<ResponseResultOrderResponse>
export type GetOrderItemsResult = AxiosResponse<ResponseResultListOrderItemResponse>
export type GetOrderByOrderNoResult = AxiosResponse<ResponseResultOrderResponse>
export type GetOrderCountResult = AxiosResponse<ResponseResultLong>
