/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  CancelOrderParams,
  CompleteOrderParams,
  CreateOrderParams,
  GetOrderByIdParams,
  GetOrderCountParams,
  GetOrderTokenParams,
  GetUserOrdersParams,
  OrderRequest,
  PayOrderParams,
  ResponseResultListOrderItemResponse,
  ResponseResultLong,
  ResponseResultOrderResponse,
  ResponseResultPageOrderResponse,
  ResponseResultString
} from '.././models';

import { customAxiosInstance } from '../../services/api';



  export const getOrderManagement = () => {
/**
 * Mark order as shipped (Admin only)
 * @summary Ship order
 */
const shipOrder = (
    orderId: number,
 ) => {
      return customAxiosInstance<ResponseResultString>(
      {url: `/api/orders/${orderId}/ship`, method: 'PUT'
    },
      );
    }
  /**
 * Process payment for an order
 * @summary Pay order
 */
const payOrder = (
    orderId: number,
    params: PayOrderParams,
 ) => {
      return customAxiosInstance<ResponseResultString>(
      {url: `/api/orders/${orderId}/pay`, method: 'PUT',
        params
    },
      );
    }
  /**
 * Mark order as completed
 * @summary Complete order
 */
const completeOrder = (
    orderId: number,
    params: CompleteOrderParams,
 ) => {
      return customAxiosInstance<ResponseResultString>(
      {url: `/api/orders/${orderId}/complete`, method: 'PUT',
        params
    },
      );
    }
  /**
 * Cancel an order
 * @summary Cancel order
 */
const cancelOrder = (
    orderId: number,
    params: CancelOrderParams,
 ) => {
      return customAxiosInstance<ResponseResultString>(
      {url: `/api/orders/${orderId}/cancel`, method: 'PUT',
        params
    },
      );
    }
  /**
 * Get paginated list of user's orders
 * @summary Get user orders
 */
const getUserOrders = (
    params: GetUserOrdersParams,
 ) => {
      return customAxiosInstance<ResponseResultPageOrderResponse>(
      {url: `/api/orders`, method: 'GET',
        params
    },
      );
    }
  /**
 * Create a new order from user's selected cart items
 * @summary Create order from cart
 */
const createOrder = (
    orderRequest: OrderRequest,
    params: CreateOrderParams,
 ) => {
      return customAxiosInstance<ResponseResultOrderResponse>(
      {url: `/api/orders`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: orderRequest,
        params
    },
      );
    }
  /**
 * @summary Generate token for creating order
 */
const getOrderToken = (
    params: GetOrderTokenParams,
 ) => {
      return customAxiosInstance<ResponseResultString>(
      {url: `/api/orders/generateOrderToken`, method: 'POST',
        params
    },
      );
    }
  /**
 * Get specific order details
 * @summary Get order by ID
 */
const getOrderById = (
    orderId: number,
    params: GetOrderByIdParams,
 ) => {
      return customAxiosInstance<ResponseResultOrderResponse>(
      {url: `/api/orders/${orderId}`, method: 'GET',
        params
    },
      );
    }
  /**
 * Get all items in an order
 * @summary Get order items
 */
const getOrderItems = (
    orderId: number,
 ) => {
      return customAxiosInstance<ResponseResultListOrderItemResponse>(
      {url: `/api/orders/${orderId}/items`, method: 'GET'
    },
      );
    }
  /**
 * Get order details by order number
 * @summary Get order by order number
 */
const getOrderByOrderNo = (
    orderNo: string,
 ) => {
      return customAxiosInstance<ResponseResultOrderResponse>(
      {url: `/api/orders/orderNo/${orderNo}`, method: 'GET'
    },
      );
    }
  /**
 * Get total order count for user
 * @summary Get order count
 */
const getOrderCount = (
    params: GetOrderCountParams,
 ) => {
      return customAxiosInstance<ResponseResultLong>(
      {url: `/api/orders/count`, method: 'GET',
        params
    },
      );
    }
  return {shipOrder,payOrder,completeOrder,cancelOrder,getUserOrders,createOrder,getOrderToken,getOrderById,getOrderItems,getOrderByOrderNo,getOrderCount}};
export type ShipOrderResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOrderManagement>['shipOrder']>>>
export type PayOrderResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOrderManagement>['payOrder']>>>
export type CompleteOrderResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOrderManagement>['completeOrder']>>>
export type CancelOrderResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOrderManagement>['cancelOrder']>>>
export type GetUserOrdersResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOrderManagement>['getUserOrders']>>>
export type CreateOrderResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOrderManagement>['createOrder']>>>
export type GetOrderTokenResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOrderManagement>['getOrderToken']>>>
export type GetOrderByIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOrderManagement>['getOrderById']>>>
export type GetOrderItemsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOrderManagement>['getOrderItems']>>>
export type GetOrderByOrderNoResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOrderManagement>['getOrderByOrderNo']>>>
export type GetOrderCountResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOrderManagement>['getOrderCount']>>>
