/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AddressRequest,
  CreateAddressParams,
  DeleteAddressParams,
  GetAddressByIdParams,
  GetAddressCountParams,
  GetDefaultAddressParams,
  GetUserAddressesParams,
  ResponseResultAddressResponse,
  ResponseResultListAddressResponse,
  ResponseResultLong,
  ResponseResultString,
  SetDefaultAddressParams,
  UpdateAddressParams
} from '.././models';




  export const getAddressManagement = () => {
/**
 * Get specific address details
 * @summary Get address by ID
 */
const getAddressById = <TData = AxiosResponse<ResponseResultAddressResponse>>(
    addressId: number,
    params: GetAddressByIdParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/addresses/${addressId}`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Update an existing address
 * @summary Update address
 */
const updateAddress = <TData = AxiosResponse<ResponseResultAddressResponse>>(
    addressId: number,
    addressRequest: AddressRequest,
    params: UpdateAddressParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `/api/addresses/${addressId}`,
      addressRequest,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Delete a shipping address
 * @summary Delete address
 */
const deleteAddress = <TData = AxiosResponse<ResponseResultString>>(
    addressId: number,
    params: DeleteAddressParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/api/addresses/${addressId}`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Set an address as default
 * @summary Set default address
 */
const setDefaultAddress = <TData = AxiosResponse<ResponseResultString>>(
    addressId: number,
    params: SetDefaultAddressParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `/api/addresses/${addressId}/default`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Get all addresses for a user
 * @summary Get user addresses
 */
const getUserAddresses = <TData = AxiosResponse<ResponseResultListAddressResponse>>(
    params: GetUserAddressesParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/addresses`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Add a new shipping address for user
 * @summary Create new address
 */
const createAddress = <TData = AxiosResponse<ResponseResultAddressResponse>>(
    addressRequest: AddressRequest,
    params: CreateAddressParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/addresses`,
      addressRequest,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Get user's default shipping address
 * @summary Get default address
 */
const getDefaultAddress = <TData = AxiosResponse<ResponseResultAddressResponse>>(
    params: GetDefaultAddressParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/addresses/default`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Get total number of addresses for user
 * @summary Get address count
 */
const getAddressCount = <TData = AxiosResponse<ResponseResultLong>>(
    params: GetAddressCountParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/addresses/count`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
return {getAddressById,updateAddress,deleteAddress,setDefaultAddress,getUserAddresses,createAddress,getDefaultAddress,getAddressCount}};
export type GetAddressByIdResult = AxiosResponse<ResponseResultAddressResponse>
export type UpdateAddressResult = AxiosResponse<ResponseResultAddressResponse>
export type DeleteAddressResult = AxiosResponse<ResponseResultString>
export type SetDefaultAddressResult = AxiosResponse<ResponseResultString>
export type GetUserAddressesResult = AxiosResponse<ResponseResultListAddressResponse>
export type CreateAddressResult = AxiosResponse<ResponseResultAddressResponse>
export type GetDefaultAddressResult = AxiosResponse<ResponseResultAddressResponse>
export type GetAddressCountResult = AxiosResponse<ResponseResultLong>
