/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  AddressRequest,
  CreateAddressParams,
  DeleteAddressParams,
  GetAddressByIdParams,
  GetAddressCountParams,
  GetDefaultAddressParams,
  GetUserAddressesParams,
  ResponseResultAddressResponse,
  ResponseResultListAddressResponse,
  ResponseResultLong,
  ResponseResultString,
  SetDefaultAddressParams,
  UpdateAddressParams
} from '.././models';

import { customAxiosInstance } from '../../services/api';



  export const getAddressManagement = () => {
/**
 * Get specific address details
 * @summary Get address by ID
 */
const getAddressById = (
    addressId: number,
    params: GetAddressByIdParams,
 ) => {
      return customAxiosInstance<ResponseResultAddressResponse>(
      {url: `/api/addresses/${addressId}`, method: 'GET',
        params
    },
      );
    }
  /**
 * Update an existing address
 * @summary Update address
 */
const updateAddress = (
    addressId: number,
    addressRequest: AddressRequest,
    params: UpdateAddressParams,
 ) => {
      return customAxiosInstance<ResponseResultAddressResponse>(
      {url: `/api/addresses/${addressId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: addressRequest,
        params
    },
      );
    }
  /**
 * Delete a shipping address
 * @summary Delete address
 */
const deleteAddress = (
    addressId: number,
    params: DeleteAddressParams,
 ) => {
      return customAxiosInstance<ResponseResultString>(
      {url: `/api/addresses/${addressId}`, method: 'DELETE',
        params
    },
      );
    }
  /**
 * Set an address as default
 * @summary Set default address
 */
const setDefaultAddress = (
    addressId: number,
    params: SetDefaultAddressParams,
 ) => {
      return customAxiosInstance<ResponseResultString>(
      {url: `/api/addresses/${addressId}/default`, method: 'PUT',
        params
    },
      );
    }
  /**
 * Get all addresses for a user
 * @summary Get user addresses
 */
const getUserAddresses = (
    params: GetUserAddressesParams,
 ) => {
      return customAxiosInstance<ResponseResultListAddressResponse>(
      {url: `/api/addresses`, method: 'GET',
        params
    },
      );
    }
  /**
 * Add a new shipping address for user
 * @summary Create new address
 */
const createAddress = (
    addressRequest: AddressRequest,
    params: CreateAddressParams,
 ) => {
      return customAxiosInstance<ResponseResultAddressResponse>(
      {url: `/api/addresses`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addressRequest,
        params
    },
      );
    }
  /**
 * Get user's default shipping address
 * @summary Get default address
 */
const getDefaultAddress = (
    params: GetDefaultAddressParams,
 ) => {
      return customAxiosInstance<ResponseResultAddressResponse>(
      {url: `/api/addresses/default`, method: 'GET',
        params
    },
      );
    }
  /**
 * Get total number of addresses for user
 * @summary Get address count
 */
const getAddressCount = (
    params: GetAddressCountParams,
 ) => {
      return customAxiosInstance<ResponseResultLong>(
      {url: `/api/addresses/count`, method: 'GET',
        params
    },
      );
    }
  return {getAddressById,updateAddress,deleteAddress,setDefaultAddress,getUserAddresses,createAddress,getDefaultAddress,getAddressCount}};
export type GetAddressByIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAddressManagement>['getAddressById']>>>
export type UpdateAddressResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAddressManagement>['updateAddress']>>>
export type DeleteAddressResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAddressManagement>['deleteAddress']>>>
export type SetDefaultAddressResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAddressManagement>['setDefaultAddress']>>>
export type GetUserAddressesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAddressManagement>['getUserAddresses']>>>
export type CreateAddressResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAddressManagement>['createAddress']>>>
export type GetDefaultAddressResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAddressManagement>['getDefaultAddress']>>>
export type GetAddressCountResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAddressManagement>['getAddressCount']>>>
