/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  CheckoutRequest,
  CreateCheckoutSessionParams,
  GetPaymentByOrderIdParams,
  RefundRequest,
  ResponseResultCheckoutResponse,
  ResponseResultPaymentResponse,
  ResponseResultRefundResponse
} from '.././models';

import { customAxiosInstance } from '../../services/api';



  export const getPaymentManagement = () => {
/**
 * Process refund for a payment (Admin only)
 * @summary Process refund
 */
const processRefund = (
    paymentId: number,
    refundRequest: RefundRequest,
 ) => {
      return customAxiosInstance<ResponseResultRefundResponse>(
      {url: `/api/payments/${paymentId}/refund`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refundRequest
    },
      );
    }
  /**
 * Create Stripe Checkout session for an order
 * @summary Create checkout session
 */
const createCheckoutSession = (
    checkoutRequest: CheckoutRequest,
    params: CreateCheckoutSessionParams,
 ) => {
      return customAxiosInstance<ResponseResultCheckoutResponse>(
      {url: `/api/payments/checkout`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: checkoutRequest,
        params
    },
      );
    }
  /**
 * Retrieve payment information for an order
 * @summary Get payment by order ID
 */
const getPaymentByOrderId = (
    orderId: number,
    params: GetPaymentByOrderIdParams,
 ) => {
      return customAxiosInstance<ResponseResultPaymentResponse>(
      {url: `/api/payments/order/${orderId}`, method: 'GET',
        params
    },
      );
    }
  return {processRefund,createCheckoutSession,getPaymentByOrderId}};
export type ProcessRefundResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPaymentManagement>['processRefund']>>>
export type CreateCheckoutSessionResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPaymentManagement>['createCheckoutSession']>>>
export type GetPaymentByOrderIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPaymentManagement>['getPaymentByOrderId']>>>
