/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CheckoutRequest,
  CreateCheckoutSessionParams,
  GetPaymentByOrderIdParams,
  RefundRequest,
  ResponseResultCheckoutResponse,
  ResponseResultPaymentResponse,
  ResponseResultRefundResponse
} from '.././models';




  export const getPaymentManagement = () => {
/**
 * Process refund for a payment (Admin only)
 * @summary Process refund
 */
const processRefund = <TData = AxiosResponse<ResponseResultRefundResponse>>(
    paymentId: number,
    refundRequest: RefundRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/payments/${paymentId}/refund`,
      refundRequest,options
    );
  }
/**
 * Create Stripe Checkout session for an order
 * @summary Create checkout session
 */
const createCheckoutSession = <TData = AxiosResponse<ResponseResultCheckoutResponse>>(
    checkoutRequest: CheckoutRequest,
    params: CreateCheckoutSessionParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/payments/checkout`,
      checkoutRequest,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Retrieve payment information for an order
 * @summary Get payment by order ID
 */
const getPaymentByOrderId = <TData = AxiosResponse<ResponseResultPaymentResponse>>(
    orderId: number,
    params: GetPaymentByOrderIdParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/payments/order/${orderId}`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
return {processRefund,createCheckoutSession,getPaymentByOrderId}};
export type ProcessRefundResult = AxiosResponse<ResponseResultRefundResponse>
export type CreateCheckoutSessionResult = AxiosResponse<ResponseResultCheckoutResponse>
export type GetPaymentByOrderIdResult = AxiosResponse<ResponseResultPaymentResponse>
