/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AddToCartParams,
  CartItemRequest,
  ClearCartParams,
  GetCartParams,
  RemoveFromCartParams,
  ResponseResultCartResponse,
  ResponseResultString,
  UpdateCartItemParams,
  UpdateItemSelectionParams
} from '.././models';




  export const getShoppingCartManagement = () => {
/**
 * @summary Update cart item quantity
 */
const updateCartItem = <TData = AxiosResponse<ResponseResultCartResponse>>(
    cartItemId: number,
    params: UpdateCartItemParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `/api/cart/update/${cartItemId}`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * @summary Update item selection status
 */
const updateItemSelection = <TData = AxiosResponse<ResponseResultString>>(
    cartItemId: number,
    params: UpdateItemSelectionParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `/api/cart/select/${cartItemId}`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * @summary Add product to cart
 */
const addToCart = <TData = AxiosResponse<ResponseResultCartResponse>>(
    cartItemRequest: CartItemRequest,
    params: AddToCartParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/cart/add`,
      cartItemRequest,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * @summary Get user cart
 */
const getCart = <TData = AxiosResponse<ResponseResultCartResponse>>(
    params: GetCartParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/cart`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * @summary Remove item from cart
 */
const removeFromCart = <TData = AxiosResponse<ResponseResultCartResponse>>(
    cartItemId: number,
    params: RemoveFromCartParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/api/cart/remove/${cartItemId}`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * @summary Clear user cart
 */
const clearCart = <TData = AxiosResponse<ResponseResultString>>(
    params: ClearCartParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/api/cart/clear`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
return {updateCartItem,updateItemSelection,addToCart,getCart,removeFromCart,clearCart}};
export type UpdateCartItemResult = AxiosResponse<ResponseResultCartResponse>
export type UpdateItemSelectionResult = AxiosResponse<ResponseResultString>
export type AddToCartResult = AxiosResponse<ResponseResultCartResponse>
export type GetCartResult = AxiosResponse<ResponseResultCartResponse>
export type RemoveFromCartResult = AxiosResponse<ResponseResultCartResponse>
export type ClearCartResult = AxiosResponse<ResponseResultString>
