/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  AddToCartParams,
  CartItemRequest,
  ClearCartParams,
  GetCartParams,
  RemoveFromCartParams,
  ResponseResultCartResponse,
  ResponseResultString,
  UpdateCartItemParams,
  UpdateItemSelectionParams
} from '.././models';

import { customAxiosInstance } from '../../services/api';



  export const getShoppingCartManagement = () => {
/**
 * @summary Update cart item quantity
 */
const updateCartItem = (
    cartItemId: number,
    params: UpdateCartItemParams,
 ) => {
      return customAxiosInstance<ResponseResultCartResponse>(
      {url: `/api/cart/update/${cartItemId}`, method: 'PUT',
        params
    },
      );
    }
  /**
 * @summary Update item selection status
 */
const updateItemSelection = (
    cartItemId: number,
    params: UpdateItemSelectionParams,
 ) => {
      return customAxiosInstance<ResponseResultString>(
      {url: `/api/cart/select/${cartItemId}`, method: 'PUT',
        params
    },
      );
    }
  /**
 * @summary Add product to cart
 */
const addToCart = (
    cartItemRequest: CartItemRequest,
    params: AddToCartParams,
 ) => {
      return customAxiosInstance<ResponseResultCartResponse>(
      {url: `/api/cart/add`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: cartItemRequest,
        params
    },
      );
    }
  /**
 * @summary Get user cart
 */
const getCart = (
    params: GetCartParams,
 ) => {
      return customAxiosInstance<ResponseResultCartResponse>(
      {url: `/api/cart`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary Remove item from cart
 */
const removeFromCart = (
    cartItemId: number,
    params: RemoveFromCartParams,
 ) => {
      return customAxiosInstance<ResponseResultCartResponse>(
      {url: `/api/cart/remove/${cartItemId}`, method: 'DELETE',
        params
    },
      );
    }
  /**
 * @summary Clear user cart
 */
const clearCart = (
    params: ClearCartParams,
 ) => {
      return customAxiosInstance<ResponseResultString>(
      {url: `/api/cart/clear`, method: 'DELETE',
        params
    },
      );
    }
  return {updateCartItem,updateItemSelection,addToCart,getCart,removeFromCart,clearCart}};
export type UpdateCartItemResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getShoppingCartManagement>['updateCartItem']>>>
export type UpdateItemSelectionResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getShoppingCartManagement>['updateItemSelection']>>>
export type AddToCartResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getShoppingCartManagement>['addToCart']>>>
export type GetCartResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getShoppingCartManagement>['getCart']>>>
export type RemoveFromCartResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getShoppingCartManagement>['removeFromCart']>>>
export type ClearCartResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getShoppingCartManagement>['clearCart']>>>
