/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  ResponseResultString,
  SeckillProductParams
} from '.././models';

import { customAxiosInstance } from '../../services/api';



  export const getSeckillProduct = () => {
/**
 * Create a new order message for rabbitmq listener
 * @summary Create order for seckilling product
 */
const seckillProduct = (
    productId: number,
    params: SeckillProductParams,
 ) => {
      return customAxiosInstance<ResponseResultString>(
      {url: `/api/seckill/${productId}`, method: 'POST',
        params
    },
      );
    }
  /**
 * Store product info and stock in Redis for seckill
 * @summary Enable product for seckill
 */
const enableProductForSeckill = (
    productId: number,
 ) => {
      return customAxiosInstance<ResponseResultString>(
      {url: `/api/seckill/enable/${productId}`, method: 'POST'
    },
      );
    }
  return {seckillProduct,enableProductForSeckill}};
export type SeckillProductResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSeckillProduct>['seckillProduct']>>>
export type EnableProductForSeckillResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSeckillProduct>['enableProductForSeckill']>>>
