/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ResponseResultString,
  SeckillProductParams
} from '.././models';




  export const getSeckillProduct = () => {
/**
 * Create a new order message for rabbitmq listener
 * @summary Create order for seckilling product
 */
const seckillProduct = <TData = AxiosResponse<ResponseResultString>>(
    productId: number,
    params: SeckillProductParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/seckill/${productId}`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Store product info and stock in Redis for seckill
 * @summary Enable product for seckill
 */
const enableProductForSeckill = <TData = AxiosResponse<ResponseResultString>>(
    productId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/seckill/enable/${productId}`,undefined,options
    );
  }
return {seckillProduct,enableProductForSeckill}};
export type SeckillProductResult = AxiosResponse<ResponseResultString>
export type EnableProductForSeckillResult = AxiosResponse<ResponseResultString>
