/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface AddressResponse {
  id?: number;
  userId?: number;
  receiverName?: string;
  receiverPhone?: string;
  province?: string;
  city?: string;
  district?: string;
  postalCode?: string;
  detailAddress?: string;
  isDefault?: number;
  createdAt?: string;
  updatedAt?: string;
  fullAddress?: string;
  defaultAddress?: boolean;
}
