/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Address data
 */
export interface AddressRequest {
  /**
   * @minLength 0
   * @maxLength 50
   */
  receiverName: string;
  /** @pattern ^(\+353|0)[1-9]\d{7,9}$ */
  receiverPhone: string;
  /**
   * @minLength 0
   * @maxLength 50
   */
  province: string;
  /**
   * @minLength 0
   * @maxLength 50
   */
  city: string;
  /**
   * @minLength 0
   * @maxLength 50
   */
  district: string;
  /** @pattern ^[A-Za-z0-9]{3}\s?[A-Za-z0-9]{4}$ */
  postalCode: string;
  /**
   * @minLength 0
   * @maxLength 255
   */
  detailAddress: string;
  isDefault?: number;
}
