/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Cart item data
 */
export interface CartItemRequest {
  productId: number;
  /** @minimum 1 */
  quantity: number;
  selected?: number;
}
