/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface CartItemResponse {
  id?: number;
  userId?: number;
  productId?: number;
  productName?: string;
  productImage?: string;
  productPrice?: number;
  quantity?: number;
  selected?: number;
  totalAmount?: number;
  createdAt?: string;
  updatedAt?: string;
}
