/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Category creation data
 */
export interface CategoryRequest {
  /**
   * Category name
   * @minLength 0
   * @maxLength 50
   */
  name: string;
  /** Parent category ID (0 for top level) */
  parentId?: number;
  /** Category icon URL */
  icon?: string;
  /** Sort order */
  sortOrder?: number;
  /** Category status (0-hidden, 1-visible) */
  status?: number;
}
