/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface CategoryResponse {
  id?: number;
  name?: string;
  parentId?: number;
  icon?: string;
  sortOrder?: number;
  status?: number;
  createdAt?: string;
  updatedAt?: string;
  subcategoryCount?: number;
}
