/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Checkout request
 */
export interface CheckoutRequest {
  orderId: number;
}
