/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type FindProductsWithPaginationParams = {
categoryId?: number;
status?: number;
page?: number;
size?: number;
sortBy?: string;
sortDir?: string;
};
