/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GetOrderCountParams = {
/**
 * User ID
 */
userId: number;
/**
 * Order status filter
 */
status?: number;
};
