/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GetUserOrdersParams = {
/**
 * User ID
 */
userId: number;
/**
 * Page number (0-based)
 */
page?: number;
/**
 * Page size
 */
size?: number;
/**
 * Order status filter
 */
status?: number;
};
