/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserResponse } from './userResponse';

export interface LoginResponse {
  token?: string;
  userInfo?: UserResponse;
  expiresIn?: number;
}
