/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface OrderItemResponse {
  id?: number;
  orderId?: number;
  orderNo?: string;
  productId?: number;
  productName?: string;
  productImage?: string;
  productPrice?: number;
  quantity?: number;
  totalAmount?: number;
  createdAt?: string;
}
