/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Order data
 */
export interface OrderRequest {
  addressId: number;
  /**
   * @minLength 0
   * @maxLength 500
   */
  comment?: string;
  freightType?: string;
}
