/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type PaymentResponseStatus = typeof PaymentResponseStatus[keyof typeof PaymentResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentResponseStatus = {
  PENDING: 'PENDING',
  SUCCEEDED: 'SUCCEEDED',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
} as const;
