/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PaymentResponseStatus } from './paymentResponseStatus';

export interface PaymentResponse {
  id?: number;
  orderId?: number;
  stripeSessionId?: string;
  stripePaymentIntentId?: string;
  amount?: number;
  currency?: string;
  status?: PaymentResponseStatus;
  createdAt?: string;
  updatedAt?: string;
}
