/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Product request
 */
export interface ProductRequest {
  /** Product name */
  name: string;
  /** Category ID */
  categoryId?: number;
  /** Product price */
  price?: number;
  originalPrice?: number;
  description?: string;
  /** Main product image */
  mainImage: string;
  images?: string;
  stock?: number;
  status?: number;
}
