/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Refund request
 */
export interface RefundRequest {
  /**
   * @minLength 0
   * @maxLength 500
   */
  reason?: string;
}
