/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface RefundResponse {
  refundId?: string;
  amount?: number;
  status?: string;
  message?: string;
}
