/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CheckoutResponse } from './checkoutResponse';

export interface ResponseResultCheckoutResponse {
  status?: number;
  msg?: string;
  data?: CheckoutResponse;
}
