/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { OrderResponse } from './orderResponse';

export interface ResponseResultOrderResponse {
  status?: number;
  msg?: string;
  data?: OrderResponse;
}
