/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageOrderResponse } from './pageOrderResponse';

export interface ResponseResultPageOrderResponse {
  status?: number;
  msg?: string;
  data?: PageOrderResponse;
}
