/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ProductResponse } from './productResponse';

export interface ResponseResultListProductResponse {
  status?: number;
  msg?: string;
  data?: ProductResponse[];
}
