/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { RefundResponse } from './refundResponse';

export interface ResponseResultRefundResponse {
  status?: number;
  msg?: string;
  data?: RefundResponse;
}
