/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AddressResponse } from './addressResponse';

export interface ResponseResultAddressResponse {
  status?: number;
  msg?: string;
  data?: AddressResponse;
}
