/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageProductResponse } from './pageProductResponse';

export interface ResponseResultPageProductResponse {
  status?: number;
  msg?: string;
  data?: PageProductResponse;
}
