/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PaymentResponse } from './paymentResponse';

export interface ResponseResultPaymentResponse {
  status?: number;
  msg?: string;
  data?: PaymentResponse;
}
