/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { OrderItemResponse } from './orderItemResponse';

export interface ResponseResultListOrderItemResponse {
  status?: number;
  msg?: string;
  data?: OrderItemResponse[];
}
