/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type UpdateCartItemParams = {
/**
 * User ID
 */
userId: number;
/**
 * Cart item quantity
 */
quantity: number;
};
