/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type UpdateItemSelectionParams = {
/**
 * User ID
 */
userId: number;
/**
 * Selection status (0 or 1)
 */
selected: number;
};
