/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * User login request
 */
export interface UserLoginRequest {
  /** Username cannot by empty */
  username: string;
  /** Password cannot be empty */
  password: string;
}
