/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  ResponseResultLoginResponse,
  ResponseResultString,
  ResponseResultUserResponse,
  UserLoginRequest,
  UserRegisterRequest
} from '.././models';

import { customAxiosInstance } from '../../services/api';



  export const getUserManagement = () => {
/**
 * Create a new user account
 * @summary Register new user
 */
const register = (
    userRegisterRequest: UserRegisterRequest,
 ) => {
      return customAxiosInstance<ResponseResultString>(
      {url: `/api/users/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userRegisterRequest
    },
      );
    }
  /**
 * Invalidate JWT token and logout user
 * @summary User logout
 */
const logout = (
    
 ) => {
      return customAxiosInstance<ResponseResultString>(
      {url: `/api/users/logout`, method: 'POST'
    },
      );
    }
  /**
 * Authenticate user and return JWT token
 * @summary User login
 */
const login = (
    userLoginRequest: UserLoginRequest,
 ) => {
      return customAxiosInstance<ResponseResultLoginResponse>(
      {url: `/api/users/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userLoginRequest
    },
      );
    }
  /**
 * @summary Find user by username
 */
const findUserByUsername = (
    username: string,
 ) => {
      return customAxiosInstance<ResponseResultUserResponse>(
      {url: `/api/users/${username}`, method: 'GET'
    },
      );
    }
  /**
 * Test UserController
 * @summary A test api
 */
const test = (
    
 ) => {
      return customAxiosInstance<ResponseResultString>(
      {url: `/api/users/test`, method: 'GET'
    },
      );
    }
  return {register,logout,login,findUserByUsername,test}};
export type RegisterResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUserManagement>['register']>>>
export type LogoutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUserManagement>['logout']>>>
export type LoginResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUserManagement>['login']>>>
export type FindUserByUsernameResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUserManagement>['findUserByUsername']>>>
export type TestResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUserManagement>['test']>>>
