/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ResponseResultLoginResponse,
  ResponseResultString,
  ResponseResultUserResponse,
  UserLoginRequest,
  UserRegisterRequest
} from '.././models';




  export const getUserManagement = () => {
/**
 * Create a new user account
 * @summary Register new user
 */
const register = <TData = AxiosResponse<ResponseResultString>>(
    userRegisterRequest: UserRegisterRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/users/register`,
      userRegisterRequest,options
    );
  }
/**
 * Invalidate JWT token and logout user
 * @summary User logout
 */
const logout = <TData = AxiosResponse<ResponseResultString>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/users/logout`,undefined,options
    );
  }
/**
 * Authenticate user and return JWT token
 * @summary User login
 */
const login = <TData = AxiosResponse<ResponseResultLoginResponse>>(
    userLoginRequest: UserLoginRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/users/login`,
      userLoginRequest,options
    );
  }
/**
 * @summary Find user by username
 */
const findUserByUsername = <TData = AxiosResponse<ResponseResultUserResponse>>(
    username: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/users/${username}`,options
    );
  }
/**
 * Test UserController
 * @summary A test api
 */
const test = <TData = AxiosResponse<ResponseResultString>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/users/test`,options
    );
  }
return {register,logout,login,findUserByUsername,test}};
export type RegisterResult = AxiosResponse<ResponseResultString>
export type LogoutResult = AxiosResponse<ResponseResultString>
export type LoginResult = AxiosResponse<ResponseResultLoginResponse>
export type FindUserByUsernameResult = AxiosResponse<ResponseResultUserResponse>
export type TestResult = AxiosResponse<ResponseResultString>
